# Generated by Django 5.0.2 on 2024-06-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_data',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tudu_app.user_data'),
        ),
    ]
