# Generated by Django 5.0.2 on 2024-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu_app', '0005_tasks_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_type_lists',
            name='google_user',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='tasks_data',
            name='google_user',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
