# Generated by Django 5.0.2 on 2024-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu_app', '0008_remove_task_type_lists_google_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_type_lists',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks_data',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
